### ISSUE TITLE
Connection reset error

### ISSUE THREAD

**Issue by william20111** [sol1/flapjack-icinga2#2]
Finished with error // Post https://monitor:5665/v1/events?queue=flapjack&types=CheckResult&types=StateChange: dial tcp monitor:5665: getsockopt: connection reset by peer

Finished with error // Post https://monitor:5665/v1/events?queue=flapjack&types=CheckResult&types=StateChange: read tcp monitor:58514->monitor:5665: read: connection reset by peer

Been getting quite frequent crashes here is two different connection resets while running in debug mode...

Cheers
Will

**Comment by william20111** [comment]
```
api_client := ApiClient{config: config, redis: transport}
api_client.Connect(finished)

select {
case <-sigs:
    log.Println("Interrupted, cancelling request")
    // TODO determine if request not currently active...
    api_client.Cancel()
case err := <-finished:
    if config.Debug {
        log.Printf("Finished with error // %s\n", err)
    }
}
```

Looks like the error is generated here.

**Comment by ali-graham** [comment]
Hmm, we might need better error handling in the case of connection interruption, disconnects, etc. I'll have a look in the next couple of days. (Sorry about the delay, I need to turn mail on for notifications from this repo.)

**Comment by william20111** [comment]
Its no bother, im now running it under supervisor so its just restarting it when it falls over. I would have tried to fix it myself but golang is pretty new to me!

**Comment by ali-graham** [comment]
Is this after it's been running for a while? It'd be useful to see a bit more context from the debug log, to know whether it's consistently happening in the same place or not. (Similarly, some way to reproduce would be good -- I tried stopping Icinga and/or Redis while things were running, but I didn't see those errors.)

The error indicates that the connection has closed prematurely, but that is most likely down to errors in the way I've set up the code. I've tweaked things slightly so that the channel that catches the errors isn't buffered, which may help. I've been trying to keep things fairly simple, as I'm fairly new to Golang as well :smile:

**Comment by william20111** [comment]
It usually fails for me within 24 hours. Although i put a dirty hack in after some brief golang reading. So that it just retrys the connection again if it has an err....and if it fails a second time it raises exception.  its been running for 2 days solid now...

If/when it fails again ill see ill grab the logs and attach them

**Comment by william20111** [comment]
Turns out my fix doesnt work. I will clone the new repo and see if the buffer fix works. 

Finished with error // Post https://monitor:5665/v1/events?queue=flapjack&types=CheckResult&types=StateChange: dial tcp monitor:5665: getsockopt: connection refused

**Comment by william20111** [comment]
Reckon that buffer fix you entered is certainly doing something. Its been flawless since i started it 4 days ago.

**Comment by ali-graham** [comment]
Ah, long may it continue! Might have just been a 'thinko' on my part initially, I know what I thought was happening but on review the code was diverging slightly from my understanding.

**Comment by william20111** [comment]
So it crashed exactly 7 days after starting it. 

2016/03/25 09:41:50 
2016/04/01 09:41:17 

Start and then the date that it was restarted by supervisord. Huge improvement from before
